#!/bin/bash

sudo echo "ServerAliveInterval 60" >> /etc/ssh/ssh_config
sudo echo "ServerAliveCountMax 3600" >> /etc/ssh/ssh_config
sudo cp *.list /etc/apt/sources.list.d
sudo chmod +x HandBrakeCLI
sudo chmod +x start
sudo cp HandBrakeCLI /usr/local/bin/.
sudo mkdir -p /mnt/jenkins
sudo chmod -R 777 /mnt/jenkins
sudo apt-get update && sudo apt-get -y install openjdk-7-jre sshpass git subversion yasm build-essential autoconf libtool zlib1g-dev libbz2-dev libxml2-dev libogg-dev libtheora-dev libvorbis-dev libsamplerate-dev libfribidi-dev libfreetype6-dev libfontconfig1-dev libass-dev libjansson-dev libmp3lame-dev libx264-dev zip unzip tar gzip
cd /usr/src
sudo apt-get -y build-dep libx264-142 && sudo apt-get -y source libx264-142
sudo add-apt-repository -y ppa:mc3man/trusty-media && sudo apt-get update && sudo apt-get -y install ffmpeg
cd /home/ubuntu/workspace
sudo cp libx264.so.142 /usr/lib/x86_64-linux-gnu/
ls -l /usr/lib/x86_64-linux-gnu/*libx264*


